/************************************
**********TIMEZONE SETTINGS**********

This file contains all possible cities and their respective timezones.
Moment-Timezone will handle the offsets and DST.
************************************/

export const cities = [
  { name: "New York", timezone: "America/New_York" },
  { name: "Los Angeles", timezone: "America/Los_Angeles" },
  { name: "Chicago", timezone: "America/Chicago" },
  { name: "Houston", timezone: "America/Chicago" },
  { name: "Phoenix", timezone: "America/Phoenix" },
  { name: "London", timezone: "Europe/London" },
  { name: "Paris", timezone: "Europe/Paris" },
  { name: "Berlin", timezone: "Europe/Berlin" },
  { name: "Kyiv", timezone: "Europe/Kiev" },
  { name: "Moscow", timezone: "Europe/Moscow" },
  { name: "Seoul", timezone: "Asia/Seoul" },
  { name: "Sydney", timezone: "Australia/Sydney" },
  { name: "Dubai", timezone: "Asia/Dubai" },
  { name: "Singapore", timezone: "Asia/Singapore" },
  { name: "Mumbai", timezone: "Asia/Kolkata" },
  { name: "Cape Town", timezone: "Africa/Johannesburg" },
  { name: "Rio de Janeiro", timezone: "America/Sao_Paulo" },
  { name: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Mexico City", timezone: "America/Mexico_City" },
  { name: "Toronto", timezone: "America/Toronto" },
  { name: "San Francisco", timezone: "America/Los_Angeles" },
  { name: "Madrid", timezone: "Europe/Madrid" },
  { name: "Rome", timezone: "Europe/Rome" },
  { name: "Cairo", timezone: "Africa/Cairo" },
  { name: "Istanbul", timezone: "Europe/Istanbul" },
  { name: "Jakarta", timezone: "Asia/Jakarta" },
  { name: "Bangkok", timezone: "Asia/Bangkok" },
  { name: "Hong Kong", timezone: "Asia/Hong_Kong" },
  { name: "Kuala Lumpur", timezone: "Asia/Kuala_Lumpur" },
  { name: "Lagos", timezone: "Africa/Lagos" },
  { name: "Nairobi", timezone: "Africa/Nairobi" },
  { name: "Manila", timezone: "Asia/Manila" },
  { name: "Athens", timezone: "Europe/Athens" },
  { name: "Lima", timezone: "America/Lima" },
  { name: "Santiago", timezone: "America/Santiago" },
  { name: "Caracas", timezone: "America/Caracas" },
  { name: "Bogotá", timezone: "America/Bogota" },
  { name: "Tehran", timezone: "Asia/Tehran" },
  { name: "Colombo", timezone: "Asia/Colombo" },
  { name: "Chennai", timezone: "Asia/Kolkata" },
  { name: "Dhaka", timezone: "Asia/Dhaka" },
  { name: "Chongqing", timezone: "Asia/Chongqing" },
  { name: "Karachi", timezone: "Asia/Karachi" },
  { name: "Auckland", timezone: "Pacific/Auckland" },
  { name: "Wellington", timezone: "Pacific/Wellington" },
  { name: "Brisbane", timezone: "Australia/Brisbane" },
  { name: "Melbourne", timezone: "Australia/Melbourne" },
  { name: "Adelaide", timezone: "Australia/Adelaide" },
  { name: "Perth", timezone: "Australia/Perth" },
  { name: "Vancouver", timezone: "America/Vancouver" },
  { name: "Montreal", timezone: "America/Toronto" },
  { name: "Calcutta", timezone: "Asia/Kolkata" },
  { name: "Tokyo", timezone: "Asia/Tokyo" },
];

export const objQty = cities.length;
